name: utopia_wm
description: Pangolin-desktop wm interface and hierarchy provider
version: 2.2.0+5

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.10.0
  provider: ^6.0.3
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
