import 'package:flutter/foundation.dart';
import 'package:utopia_wm/src/entry.dart';
import 'package:utopia_wm/src/events/base.dart';

/// Mixin to add shorthands for events generated by the [ResizeWindowFeature] feature.
mixin ResizeEvents on WindowEventHandler {
  @override
  void onEvent(WindowEvent event) {
    return switch (event) {
      WindowResizeStartEvent() => onStartResize(),
      WindowResizeEndEvent() => onEndResize(),
      _ => super.onEvent(event),
    };
  }

  /// Handler for [WindowResizeStartEvent] events.
  @protected
  void onStartResize() {}

  /// Handler for [WindowResizeEndEvent] events.
  @protected
  void onEndResize() {}
}

/// Event generated when the user starts resizing the window.
class WindowResizeStartEvent extends WindowEvent {
  const WindowResizeStartEvent({required super.timestamp});
}

/// Event generated when the user is done resizing the window.
class WindowResizeEndEvent extends WindowEvent {
  const WindowResizeEndEvent({required super.timestamp});
}
